name: timetable
description: '📅 Customizable, animated calendar widget including day & week views'
version: 0.2.7
homepage: https://github.com/JonasWanke/timetable

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  black_hole_flutter: ^0.3.0
  collection: ^1.15.0
  dart_date: ^1.1.0-nullsafety.0
  flutter:
    sdk: flutter
  intl: ^0.17.0
  meta: ^1.3.0
  rxdart: ^0.26.0
  supercharged: ^2.0.0
  tuple: ^2.0.0

dev_dependencies:
  extra_pedantic: ^1.3.0
  flutter_test:
    sdk: flutter
  glados: ^1.0.0
  test: ^1.9.4
  tuple_glados: ^1.0.0
