name: timetable
description: "📅 Customizable, animated calendar widget including day, week and month views"
version: 0.0.1
homepage: https://github.com/JonasWanke/timetable

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  time_machine: ^0.9.12
  meta: ^1.1.8
