name: timetable
description: "📅 Customizable, animated calendar widget including day & week views"
version: 0.1.1
homepage: https://github.com/JonasWanke/timetable

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  black_hole_flutter: ^0.2.5
  collection: ^1.14.11
  dartx: ^0.2.0
  meta: ^1.1.8
  pedantic: ^1.9.0
  rxdart: ^0.23.1
  time_machine: ^0.9.12
