name: remind_timetable
description: ReMinds timetable
version: 1.1.0-alpha
repository: https://github.com/Allistic/timetable

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  async: ^2.6.0
  black_hole_flutter: ^1.0.0
  collection: ^1.15.0
  dart_date: ^1.1.0
  dartx: ^1.0.0
  flutter:
    sdk: flutter
  flutter_layout_grid: ^2.0.0
  intl: ^0.17.0
  meta: ^1.3.0
  tuple: ^2.0.0

dev_dependencies:
  dart_code_metrics: ^5.0.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  glados: ^1.0.0
  test: ^1.9.4
  tuple_glados: ^1.0.0
